version: "3.5"

services:
  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
    networks:
      - trashRouting

networks:
  trashRouting:
    name: trashRouting-network
    external: true