version: "3.5"

services:
  trash-routing-api:
    build:
      context: .
      dockerfile: ./Dockerfile-api
    ports:
      - '5000:5000'  
    networks:
      - trashRouting

networks:
  trashRouting:
    name: trashRouting-network
    external: true