FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 5010

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["TrashRouting.Cluster/TrashRouting.Cluster.csproj", "TrashRouting.Cluster/"]
COPY ["TrashRouting.Common/TrashRouting.Common.csproj", "TrashRouting.Common/"]
RUN dotnet restore "TrashRouting.Cluster/TrashRouting.Cluster.csproj"
COPY . .
WORKDIR "/src/TrashRouting.Cluster"
RUN dotnet build "TrashRouting.Cluster.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "TrashRouting.Cluster.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENV ASPNETCORE_URLS http://*:5010
ENTRYPOINT ["dotnet", "TrashRouting.Cluster.dll"]