version: "3.5"

services:
  trash-routing-cluster:
    build:
      context: .
      dockerfile: ./Dockerfile-routes
    ports:
      - '5020:5020'  
    networks:
      - trashRouting

networks:
  trashRouting:
    name: trashRouting-network
    external: true