FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 5020

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["TrashRouting.Routes/TrashRouting.Routes.csproj", "TrashRouting.Routes/"]
COPY ["TrashRouting.Common/TrashRouting.Common.csproj", "TrashRouting.Common/"]
RUN dotnet restore "TrashRouting.Routes/TrashRouting.Routes.csproj"
COPY . .
WORKDIR "/src/TrashRouting.Routes"
RUN dotnet build "TrashRouting.Routes.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "TrashRouting.Routes.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENV ASPNETCORE_URLS http://*:5020
ENTRYPOINT ["dotnet", "TrashRouting.Routes.dll"]