version: "3.5"

services:
  trash-routing-api:
    build:
      context: .
      dockerfile: ./Dockerfile-api
    ports:
      - '5000:5000'
    networks:
      - trashRouting
    environment:
      - 'ASPNETCORE_ENVIRONMENT=docker'

  trash-routing-cluster:
    build:
      context: .
      dockerfile: ./Dockerfile-cluster
    ports:
      - '5010:5010'  
    networks:
      - trashRouting
    environment:
      - 'ASPNETCORE_ENVIRONMENT=docker'
      
  trash-routing-routes:
    build:
      context: .
      dockerfile: ./Dockerfile-routes
    ports:
      - '5020:5020'  
    networks:
      - trashRouting
    environment:
      - 'ASPNETCORE_ENVIRONMENT=docker'
      
  trash-routing-sync:
    build:
      context: .
      dockerfile: ./Dockerfile-sync
    ports:
      - '5030:5030'  
    networks:
      - trashRouting
    environment:
      - 'ASPNETCORE_ENVIRONMENT=docker'

networks:
  trashRouting:
    name: trashRouting-network
    external: true