version: "3.5"

services:
  trash-routing-api:
    build:
      context: ./TrashRouting.Api/
      dockerfile: ./Dockerfile
    ports:
      - '5000:80'
    networks:
      - trashRouting
    environment:
      - 'EXAMPLEVARIABLE=example'

  trash-routing-cluster:
    build:
      context: ./TrashRouting.Cluster/
      dockerfile: ./Dockerfile
    ports:
      - '5010:80'  
    networks:
      - trashRouting
    environment:
      - 'EXAMPLEVARIABLE=example'
      
  trash-routing-cluster:
    build:
      context: ./TrashRouting.Cluster/
      dockerfile: ./Dockerfile
    ports:
      - '5011:80'  
    networks:
      - trashRouting
    environment:
      - 'EXAMPLEVARIABLE=example'
      
  trash-routing-routes:
    build:
      context: ./TrashRouting.Routes/
      dockerfile: ./Dockerfile
    ports:
      - '5020:80'  
    networks:
      - trashRouting
    environment:
      - 'EXAMPLEVARIABLE=example'
      
  trash-routing-sync:
    build:
      context: ./TrashRouting.Sync/
      dockerfile: ./Dockerfile
    ports:
      - '5030:80'  
    networks:
      - trashRouting
    environment:
      - 'EXAMPLEVARIABLE=example'

networks:
  trashRouting:
    name: trashRouting-network
    external: true